const PLAN_INFO_ADD = 'PLAN_INFO_ADD'
const PLAN_INFO_DEL = 'PLAN_INFO_DEL'
const PLAN_INFO_CLEAR = 'PLAN_INFO_CLEAR'
const PLAN_INFO_INIT = 'PLAN_INFO_INIT'
const PLAN_INFO_EDIT = 'PLAN_INFO_EDIT'

const EXERCISE_STAT_ADD = 'EXERCISE_STAT_ADD'
const EXERCISE_STAT_DEL = 'EXERCISE_STAT_DEL'
const EXERCISE_STAT_EDIT = 'EXERCISE_STAT_EDIT'
const EXERCISE_STAT_CLEAR = 'EXERCISE_STAT_CLEAR'

const exportedObject={
    PLAN_INFO_ADD,
    PLAN_INFO_DEL,
    PLAN_INFO_CLEAR,
    PLAN_INFO_INIT,
    PLAN_INFO_EDIT,

    EXERCISE_STAT_ADD,
    EXERCISE_STAT_DEL,
    EXERCISE_STAT_EDIT,
    EXERCISE_STAT_CLEAR
}

export default exportedObject
