const PLAN_INFO_ADD = 'PLAN_INFO_ADD'
const PLAN_INFO_DEL = 'PLAN_INFO_DEL'
const PLAN_INFO_CLEAR = 'PLAN_INFO_CLEAR'
const PLAN_INFO_INIT = 'PLAN_INFO_INIT'
const PLAN_INFO_EDIT = 'PLAN_INFO_EDIT'

export default {
    PLAN_INFO_ADD,
    PLAN_INFO_DEL,
    PLAN_INFO_CLEAR,
    PLAN_INFO_INIT,
    PLAN_INFO_EDIT
}
