const PLAN_ADD = 'PLAN_ADD'
const PLAN_DELETE = 'PLAN_DELETE'
const PLAN_EDIT = 'PLAN_EDIT'
const PLAN_CLEAR = 'PLAN_CLEAR'

const PLAN_EXERCISE_ADD = 'PLAN_EXERCISE_ADD'
const PLAN_EXERCISE_DELETE = 'PLAN_EXERCISE_DELETE'
const PLAN_EXERCISE_EDIT = 'PLAN_EXERCISE_EDIT'
const PLAN_EXERCISE_CLEAR = 'PLAN_EXERCISE_CLEAR'

export default {
    PLAN_ADD,
    PLAN_DELETE,
    PLAN_EDIT,
    PLAN_CLEAR,

    PLAN_EXERCISE_ADD,
    PLAN_EXERCISE_DELETE,
    PLAN_EXERCISE_EDIT,
    PLAN_EXERCISE_CLEAR,
}
